version: '3'
services: 
    mysql:
        build: ./mysql
    nodeserver:
        build: ./node
        depends_on: 
            - mysql
      #  volumes: 
      #      - ./node:/usr/src/app
    nginx:
        build: ./nginx
        ports:
            - 8080:80
        depends_on:
            - nodeserver